server:
  port: 9201
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写
# 使用application-eureka.yml配置文件启动api-gateway服务，访问 http://localhost:9201/user-service/user/1 ，
# 可以路由到 user-service服务的 http://localhost:8201/user/1 处。
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug