server:
  port: 9201
spring:
  redis:
    host: localhost
    port: 6379
  cloud:
    gateway:
      routes:
        - id: retry_route
          uri: http://localhost:8201
          predicates:
            - Method=GET
          filters:
            - name: Retry # 过滤器名称
              args:
                retries: 1 #需要进行重试的次数。访问测试地址：http://localhost:9201/user/111 可以发现user-service控制台报错2次，说明进行了 1次重试。
                statuses: BAD_GATEWAY #根据返回哪个状态码来确定是否需要进行重试，返回状态码为5XX进行重试。
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false
logging:
  level:
    org.springframework.cloud.gateway: debug