server:
  port: 9201
service-url:
  user-service: http://localhost:8201
spring:
  cloud:
    gateway:
      routes:
        - id: remoteaddr_route
          uri: ${service-url.user-service}
          predicates:
#            - After=2022-10-28T16:30:00+08:00[Asia/Shanghai]  # 在指定时间之后的请求会匹配该路由。
#            - Before=2019-09-24T16:30:00+08:00[Asia/Shanghai]  # 在指定时间之前的请求会匹配该路由。
#            - Between=2019-09-24T16:30:00+08:00[Asia/Shanghai], 2019-09-25T16:30:00+08:00[Asia/Shanghai] # 在指定时间区间内的请求会匹配该路由。
#            - Cookie=username,macro #带有指定Cookie的请求会匹配该路由。使用curl工具发送带有cookie为username=macro的请求可以匹配该路由。curl http://localhost:9201/user/1 --cookie "username=macro"
#            - Method=GET # 发送指定方法的请求会匹配该路由。
            - RemoteAddr=192.168.6.107/24 # 从指定远程地址发起的请求可以匹配该路由。