server:
  port: 8182

spring:
  application:
    name: seata-account-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata-account
    username: root
    password: 123456


# 配置nacos注册中心和配置中心属性
seata:
  # Seata 应用编号，默认为 ${spring.application.name}
  application-id: ${spring.application.name}
  # 自定义 Seata 事务组名称，用于 TC 集群名。该配置需要与 seata-server服务端中提到的group相对应，也需要与下面的相对应
  tx-service-group: ${spring.application.name}-group
  # 是否开启Seata对数据源进行自动代理
#  enable-auto-data-source-proxy: false
  # 服务配置项
  service:
    # 虚拟组和分组的映射
    vgroupMapping:
      seata-order-service_group: default   #该配置需要与服务端提到的group相对应
  # 配置中心，需要和 seata server 保持一致
  config:
    # support: nacos, consul, apollo, zk, etcd3
    type: nacos
    nacos:
      # nacos ip:port地址
      server-addr: 127.0.0.1:8848
      namespace: #命名空间，使用默认的不用填
      group: SEATA_GROUP
      username: nacos
      password: nacos
      data-id: seataServer.properties # 与nacos配置中心指定的配置data-id名称一致
  # 配置中心，需要和 seata server 保持一致
  registry:
    # support: nacos, eureka, redis, zk, consul, etcd3, sofa
    type: nacos
    nacos:
      application: seata-server  # seata 注册服务名
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace: #命名空间，使用默认的不用填
      # cluster: default
      username: nacos
      password: nacos
#  # 以下存储配置，可以配置在nacos的 seataServer.properties
#  store:
#    # support: file 、 db 、 redis
#    mode: db
#    db:
#      datasource: druid
#      db-type: mysql
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://127.0.0.1:3306/seat-account?serverTimezone=Asia/Shanghai #填线上Mysql的IP:PORT，seata数据库名，要和前面插入seata表同一个名
#      user: root #数据库账号
#      password: 123456 #数据库密码
#      min-conn: 5
#      max-conn: 100
#      global-table: global_table
#      branch-table: branch_table
#      lock-table: lock_table
#      distributed-lock-table: distributed_lock
#      query-limit: 100
#      max-wait: 5000

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml