server:
  port: 8801
spring:
  application:
    name: zuul-proxy
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/
zuul:
  routes: #给服务配置路由
    user-service: # user-service 服务
      path: /userService/** # 将匹配/userService/**的请求路由到user-service服务上去。默认的路由规则以服务名称为匹配路径：比如 /user-service/**
    feign-service: # feign-service 服务
      path: /feignService/**   # # 将匹配/feignService/**的请求路由到 feign-service服务上去
#  ignored-services: user-service,feign-service #关闭默认路由配置
#  prefix: /proxy #给网关路由添加前缀，这样我们需要访问http://localhost:8801/proxy/userService/user/1才能访问到user-service中的接口
  sensitive-headers: Cookie,Set-Cookie,Authorization #Zuul在请求路由时，配置过滤敏感的请求头信息，设置为空就不会过滤
  add-host-header: true #设置为true重定向是会添加host请求头
  PreLogFilter: # 自定义过滤器 PreLogFilter类
    pre:
      disable: true #控制是否启用过滤器

# 通过SpringBoot Actuator来查看Zuul中的路由信息，通过访问http://localhost:8801/actuator/routes/details查看详细路由信息：
management:
  endpoints:
    web:
      exposure:
        include: 'routes'