server:
  port: 8308
spring:
  application:
    name: consul-ribbon-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
# 调用 consul-user-service 模块
service-url:
  consul-user-service: http://consul-user-service