server:
  port: 8001 #指定运行端口

spring:
  application:
    name: eureka-server #指定服务名称，如果没有配置，默认名称UNKNOWN。注意名字不要是下划线。

eureka:
  instance:
    hostname: localhost #指定主机地址
  client:
    #指定是否要从注册中心获取服务（因为当前为非集群eureka,所以不需要同步其他节点数据，默认为true）
    fetch-registry: false
    #指定是否要把当前自己注册到注册中心（因为当前项目为注册中心服务，不需要向注册中心注册自己，默认为true, 单机版注册中心不需要开启, 只有集群才开启）
    register-with-eureka: false
    # 这个如果配置的是8761（eureka默认的端口），那么可以不需要配置
    service-url:
      defaultZone: http://localhost:8001/eureka/ #配置注册中心地址, 客户端会通过这个地址进行注册
  server:
    enable-self-preservation: false #关闭保护模式

# 通过 Spring Actuator 优雅的关闭项目。使用postman发送post请求: http://localhost:8001/actuator/shutdown
management:
  endpoints:
#    所有功能默认开启
    enabled-by-default: true
#    显示所有已启用功能
    web:
      exposure:
        include: '*'