server:
  port: 8901

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git: #配置存储配置信息的Git仓库
          uri: https://gitee.com/hdutest/springcloud-test-config.git
#          username: xiaoz
#          password: xxxx
          clone-on-start: true #开启启动时直接从git获取配置
          ##搜索目录.这个目录指的是git上的目录 https://gitee.com/hdutest/springcloud-test-config.git
          search-paths:
            - config-repo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/