server:
  port: 7091

spring:
  application:
    name: seata-server

logging:
  config: classpath:logback-spring.xml
  file:
    path: ${user.home}/logs/seata
  extend:
    logstash-appender:
      destination: 127.0.0.1:4560
    kafka-appender:
      bootstrap-servers: 127.0.0.1:9092
      topic: logback_to_logstash

console:
  user:
    username: seata
    password: seata

seata:
  config:
    # support: nacos, consul, apollo, zk, etcd3
    type: nacos
    nacos:
      # nacos ip:port地址
      server-addr: 127.0.0.1:8848
      namespace: seata #命名空间，使用默认的不用填
      group: SEATA_GROUP
      username: nacos
      password: nacos
      data-id: seataServer.properties # 与nacos配置中心指定的配置data-id名称一致
  registry:
    # support: nacos, eureka, redis, zk, consul, etcd3, sofa
    type: nacos
    nacos:
      application: seata-server  # seata注册服务名
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace: seata #命名空间，使用默认的不用填
      # cluster: default
      username: nacos
      password: nacos
#  # 以下存储配置，可以配置在nacos的 seataServer.properties
  store:
    # support: file 、 db 、 redis
    mode: db
    db:
      datasource: druid
      db-type: mysql
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/seat-order?serverTimezone=Asia/Shanghai #填线上Mysql的IP:PORT，seata数据库名，要和前面插入seata表同一个名
      user: root #数据库账号
      password: 123456 #数据库密码
      min-conn: 5
      max-conn: 100
      global-table: global_table
      branch-table: branch_table
      lock-table: lock_table
      distributed-lock-table: distributed_lock
      query-limit: 100
      max-wait: 5000
  server:
    service-port: 8091 #If not configured, the default is '${server.port} + 1000'
  security:
    secretKey: SeataSecretKey0c382ef121d778043159209298fd40bf3850a017
    tokenValidityInMilliseconds: 1800000
    ignore:
      urls: /,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-fe/public/**,/api/v1/auth/login